### ISSUE TITLE
ESA 2018 5-hr Workshop

### ISSUE THREAD

**Issue by vlraymond** [NCEAS/arctic-data-outreach#30]
- pre existing content
- 5 hrs
Next steps:
- [ ] AB to provide links to content in April 2018
- [ ] ADC team can help promote
- [ ] emphasize this is an entry level training for data management

**Comment by aebudden** [comment]
@kameyer Can you add this to our training page?

**Comment by aebudden** [comment]
Wksp information not yet online so copying some details below. We do not need to create an arcticdata.io page for this one, but rather link to the ESA page when open since that is how people will register. In the interim, we can put up a summary and indicate "full details coming soon" or some such.


WK 5: "Managing Ecological Data for Effective Use and Re-Use: A Workshop for Early Career Scientists" 
Sunday, August 5, 2018
8:00 AM - 11:30 AM

Abstract: While graduate students in ecology learn about methods for collecting ecological data, there is less emphasis on managing and using the resulting data effectively. This is an increasingly important skill set; many funding agencies require data management plans, journals are requiring that data and resulting software be accessible, and society is increasingly expecting that research be reproducible. Ecologists with good data skills will be able to maximize the productivity of their research program, effectively and efficiently share their data and other research products with the scientific community, and potentially benefit from the re-use of their data by others.
The purpose of this workshop is to give attendees a set of practical tools for organizing and sharing their data through all parts of the research cycle. The target audience is early-career scientists but is open to any researchers who would benefit from developing better data management skills, including faculty who would like to teach best practices for preparing data. Topics will include data structure, quality control, data documentation, the importance of good data management practices for data sharing, collaboration, and data re-use. The workshop will be an interactive combination of presentation, discussion and activities. Participants must bring their own laptop to work on exercises. A related Inspire Session is planned and a Special Session on “Creating Effective Data Management Plans for Ecological Research” may also be useful to participants.

Speakers: Amber Budden, Matt Jones, Vanessa Raymond, Bill Michener, Stephanie Hampton, Dave Vieglais

**Comment by kameyer** [comment]
Added to the training page
